FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/HTFP.FileSpliter/HTFP.FileSpliter.csproj ./HTFP.FileSpliter/
COPY src/HTFP.Shared/HTFP.Shared.csproj ./HTFP.Shared/

RUN dotnet restore ./HTFP.FileSpliter/HTFP.FileSpliter.csproj

COPY src/ ./src/

RUN dotnet publish ./src/HTFP.FileSpliter/HTFP.FileSpliter.csproj \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:9.0 AS final
WORKDIR /app

# Copy published app
COPY --from=build /app/publish .

# Entry point
ENTRYPOINT ["dotnet", "HTFP.FileSpliter.dll"]
