FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY src/HTFP.FileSpliter/HTFP.FileSpliter.csproj ./HTFP.FileSpliter
COPY src/HTFP.Shared/HTFP.Shared.csproj ./HTFP.Shared
RUN dotnet restore ./HTFP.FileSpliter/HTFP.FileSpliter.csproj
COPY . .
RUN dotnet publish "HTFP.FileSpliter.csproj" -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:9.0 as final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "HTFP.FileSpliter.dll"]