FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY src/HTFP.Coordinator/HTFP.Coordinator.csproj ./HTFP.Coordinator/
COPY src/HTFP.Shared/HTFP.Shared.csproj ./HTFP.Shared/

RUN dotnet restore ./HTFP.Coordinator/HTFP.Coordinator.csproj

COPY . .

RUN dotnet publish ./src/HTFP.Coordinator/HTFP.Coordinator.csproj \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "HTFP.Coordinator.dll"]